// Code generated by "stringer -type=FileChangeType"; DO NOT EDIT

package messages

import "fmt"

const _FileChangeType_name = "ChangeUnknownChangeAdditionChangeRemovalChangeModification"

var _FileChangeType_index = [...]uint8{0, 13, 27, 40, 58}

func (i FileChangeType) String() string {
	if i >= FileChangeType(len(_FileChangeType_index)-1) {
		return fmt.Sprintf("FileChangeType(%d)", i)
	}
	return _FileChangeType_name[_FileChangeType_index[i]:_FileChangeType_index[i+1]]
}
